sudo: required

services:
  - docker

script:
  - docker build -t wafflespeanut/teletrader .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push wafflespeanut/teletrader
